//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HM_Api
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientAppoinment
    {
        public int Id { get; set; }
        public string Patient_Name { get; set; }
        public string Patient_CNIC { get; set; }
        public string Patient_Phone { get; set; }
        public string Appoinment_Date { get; set; }
        public Nullable<int> Doctor_Id { get; set; }
    }
}
